title: "よくやる Laravel リファクタリング"
summary: "Laravel のリファクタリングをよくするのですが、そのときによくやるリファクタリングです"
topics: ['laravel']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - require_ide_helper
  - setting_name_for_url
  - model_and_models
  - make_original_namespace
  - make_test
