title: "Laravel tips"
summary: "注意して書いている所を書いていってます。"
topics: ["php","laravel","programming"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - topics
  - namespace-at-model
#  - how-to-create-development-env
  - validation
  - order-by-created-at
  - use_dto
  - query_scope
  - look-up-table
  - nested-return-value
  - right-is-big
  - make-a-base-class
