title: "Laravel tips"
summary: "注意して書いている所を書いていってます。ラベルとして [PG] とあるのは言語・フレームワークによらない事、[Laravel] と書いているのは Laravel にのみ関係している部分です。"
topics: ["php","laravel","programming"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - topics
  - 12factor
  - namespace-at-model
  - how-to-create-development-env
  - validation
  - do-not-use-env
  - order-by-created-at
  - use_dto
  - query_scope
  - look-up-table
  - nested-return-value
  - right-is-big
  - make-a-base-class
  - seeder-is-not-testing
  - template-save-path-is-url
